[
        {"alumno":"Patricio","nota":10,"ranking":1},
        {"alumno":"Rodrigo","nota":6,"ranking":85},
        {"alumno":"Jaime","nota":2,"ranking":330},
        {"alumno":"Laura","nota":4.1,"ranking":122},
        {"alumno":"Marta","nota":8.09,"ranking":40},
        {"alumno":"Aurora","nota":4,"ranking":162},
        {"alumno":"Jesús","nota":7,"ranking":55},
        {"alumno":"María","nota":5,"ranking":100},
        {"alumno":"Mario","nota":1,"ranking":500}
      ]
